// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZEdgcgkuHpcbVEhC7BaEOWDSmRDby-c',
    appId: '1:1055666905515:web:c403d0bb71a48ea9a0f2ee',
    messagingSenderId: '1055666905515',
    projectId: 'carxv2-22bed',
    authDomain: 'carxv2-22bed.firebaseapp.com',
    databaseURL: 'https://carxv2-22bed-default-rtdb.firebaseio.com',
    storageBucket: 'carxv2-22bed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_W9d1Sr-kiDTfPJx-3fQG7223pF22bk',
    appId: '1:1055666905515:android:80f0c8bc8f904993a0f2ee',
    messagingSenderId: '1055666905515',
    projectId: 'carxv2-22bed',
    databaseURL: 'https://carxv2-22bed-default-rtdb.firebaseio.com',
    storageBucket: 'carxv2-22bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVsAZemD_ixNyKhlwEgTcnDIV2qE6Kto',
    appId: '1:1055666905515:ios:19a0df31178f6536a0f2ee',
    messagingSenderId: '1055666905515',
    projectId: 'carxv2-22bed',
    databaseURL: 'https://carxv2-22bed-default-rtdb.firebaseio.com',
    storageBucket: 'carxv2-22bed.appspot.com',
    iosBundleId: 'com.example.carxproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVsAZemD_ixNyKhlwEgTcnDIV2qE6Kto',
    appId: '1:1055666905515:ios:4c36d62c87f1f39aa0f2ee',
    messagingSenderId: '1055666905515',
    projectId: 'carxv2-22bed',
    databaseURL: 'https://carxv2-22bed-default-rtdb.firebaseio.com',
    storageBucket: 'carxv2-22bed.appspot.com',
    iosBundleId: 'com.example.carxproje.RunnerTests',
  );
}
